// <auto-generated />
using System;
using Erfa.ProductionManagement.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erfa.ProductionManagement.Persistance.Migrations.ErfaProductionDb
{
    [DbContext(typeof(ErfaProductionDbContext))]
    partial class ErfaProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("float");

                    b.Property<double>("ProductionTimeSec")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ArchivedItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionGroupHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ArchivedProductionGroups");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductionGroupHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RalGalv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionGroupHistoryId");

                    b.ToTable("ArchivedProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.Item", b =>
                {
                    b.Property<string>("ProductNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("float");

                    b.Property<double>("ProductionTimeSec")
                        .HasColumnType("float");

                    b.HasKey("ProductNumber");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ProductNumber = "XYZ123",
                            Category = "Shelv",
                            CreatedBy = "Magdalena",
                            CreatedDate = new DateTime(2023, 9, 21, 23, 33, 36, 683, DateTimeKind.Local).AddTicks(1732),
                            Description = "Very nice piece of metal",
                            LastModifiedBy = "Magdalena",
                            LastModifiedDate = new DateTime(2023, 9, 21, 23, 33, 36, 683, DateTimeKind.Local).AddTicks(1734),
                            ProductWeight = 100.0,
                            ProductionTimeSec = 100.0
                        },
                        new
                        {
                            ProductNumber = "ABC987",
                            Category = "Shelv",
                            CreatedBy = "Magdalena",
                            CreatedDate = new DateTime(2023, 9, 21, 23, 33, 36, 683, DateTimeKind.Local).AddTicks(1739),
                            Description = "Not so nice piece of metal",
                            LastModifiedBy = "Magdalena",
                            LastModifiedDate = new DateTime(2023, 9, 21, 23, 33, 36, 683, DateTimeKind.Local).AddTicks(1741),
                            ProductWeight = 50.0,
                            ProductionTimeSec = 50.0
                        });
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionGroups");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RalGalv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemProductNumber");

                    b.HasIndex("ProductionGroupId");

                    b.ToTable("ProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionItemHistory", b =>
                {
                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionGroupHistory", null)
                        .WithMany("ProductionItems")
                        .HasForeignKey("ProductionGroupHistoryId");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionItem", b =>
                {
                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Production.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemProductNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Production.ProductionGroup", null)
                        .WithMany("ProductionItems")
                        .HasForeignKey("ProductionGroupId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionGroupHistory", b =>
                {
                    b.Navigation("ProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionGroup", b =>
                {
                    b.Navigation("ProductionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
