// <auto-generated />
using Erfa.ProductionManagement.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erfa.ProductionManagement.Persistance.Migrations.ErfaAuthDb
{
    [DbContext(typeof(ErfaAuthDbContext))]
    partial class ErfaAuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ApplicationIdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationIdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "b8cd9a8d-e127-45e9-8f90-07ae1bc7d1d5",
                            ConcurrencyStamp = "1",
                            Name = "ProdAdmin",
                            NormalizedName = "ProdAdmin"
                        },
                        new
                        {
                            Id = "4864bdfb-336b-4b66-98dc-fa6ef10800a1",
                            ConcurrencyStamp = "2",
                            Name = "Worker",
                            NormalizedName = "Worker"
                        },
                        new
                        {
                            Id = "54b3795e-728f-4925-a13a-5147e9fe6fcd",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
