// <auto-generated />
using System;
using Erfa.ProductionManagement.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erfa.ProductionManagement.Persistance.Migrations
{
    [DbContext(typeof(ErfaDbContext))]
    [Migration("20230628215333_ProductionGroup_and_Hitosty_V4")]
    partial class ProductionGroup_and_Hitosty_V4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Item", b =>
                {
                    b.Property<string>("ProductNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("float");

                    b.Property<double>("ProductionTimeSec")
                        .HasColumnType("float");

                    b.HasKey("ProductNumber");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ProductNumber = "XYZ123",
                            Category = "Shelv",
                            CreatedBy = "Magdalena",
                            CreatedDate = new DateTime(2023, 6, 28, 23, 53, 33, 817, DateTimeKind.Local).AddTicks(7366),
                            Description = "Very nice piece of metal",
                            LastModifiedBy = "Magdalena",
                            LastModifiedDate = new DateTime(2023, 6, 28, 23, 53, 33, 817, DateTimeKind.Local).AddTicks(7368),
                            ProductWeight = 100.0,
                            ProductionTimeSec = 100.0
                        },
                        new
                        {
                            ProductNumber = "ABC987",
                            Category = "Shelv",
                            CreatedBy = "Magdalena",
                            CreatedDate = new DateTime(2023, 6, 28, 23, 53, 33, 817, DateTimeKind.Local).AddTicks(7374),
                            Description = "Not so nice piece of metal",
                            LastModifiedBy = "Magdalena",
                            LastModifiedDate = new DateTime(2023, 6, 28, 23, 53, 33, 817, DateTimeKind.Local).AddTicks(7376),
                            ProductWeight = 50.0,
                            ProductionTimeSec = 50.0
                        });
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("float");

                    b.Property<double>("ProductionTimeSec")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ArchivedItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionGroups");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionGroupHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ArchivedProductionGroupss");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RalGalv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemProductNumber");

                    b.HasIndex("ProductionGroupId");

                    b.ToTable("ProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductionGroupHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RalGalv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionGroupHistoryId");

                    b.ToTable("ArchivedProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionItem", b =>
                {
                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemProductNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.ProductionGroup", null)
                        .WithMany("ProductionItems")
                        .HasForeignKey("ProductionGroupId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionItemHistory", b =>
                {
                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.ProductionGroupHistory", null)
                        .WithMany("ProductionItems")
                        .HasForeignKey("ProductionGroupHistoryId");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionGroup", b =>
                {
                    b.Navigation("ProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.ProductionGroupHistory", b =>
                {
                    b.Navigation("ProductionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
