// <auto-generated />
using System;
using Erfa.ProductionManagement.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erfa.ProductionManagement.Persistance.Migrations
{
    [DbContext(typeof(ErfaDbContext))]
    [Migration("20231129031509_delete_category")]
    partial class delete_category
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("integer");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProductionTimeSec")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ArchivedItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionGroupHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("integer");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ArchivedProductionGroups");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("integer");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductionGroupHistoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductionItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RalGalv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionGroupHistoryId");

                    b.ToTable("ArchivedProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.Item", b =>
                {
                    b.Property<string>("ProductNumber")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProductionTimeSec")
                        .HasColumnType("double precision");

                    b.HasKey("ProductNumber");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ProductNumber = "XYZ123",
                            CreatedBy = "Magdalena",
                            CreatedDate = new DateTime(2023, 11, 29, 3, 15, 9, 621, DateTimeKind.Utc).AddTicks(2606),
                            Description = "Very nice piece of metal",
                            LastModifiedBy = "Magdalena",
                            LastModifiedDate = new DateTime(2023, 11, 29, 3, 15, 9, 621, DateTimeKind.Utc).AddTicks(2607),
                            MaterialProductName = "some material",
                            ProductionTimeSec = 100.0
                        },
                        new
                        {
                            ProductNumber = "ABC987",
                            CreatedBy = "Magdalena",
                            CreatedDate = new DateTime(2023, 11, 29, 3, 15, 9, 621, DateTimeKind.Utc).AddTicks(2609),
                            Description = "Not so nice piece of metal",
                            LastModifiedBy = "Magdalena",
                            LastModifiedDate = new DateTime(2023, 11, 29, 3, 15, 9, 621, DateTimeKind.Utc).AddTicks(2610),
                            MaterialProductName = "Some other material",
                            ProductionTimeSec = 50.0
                        });
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProductionGroups");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemProductNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductionGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RalGalv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Worker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemProductNumber");

                    b.HasIndex("ProductionGroupId");

                    b.ToTable("ProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionItemHistory", b =>
                {
                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionGroupHistory", null)
                        .WithMany("ProductionItems")
                        .HasForeignKey("ProductionGroupHistoryId");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionItem", b =>
                {
                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Production.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemProductNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erfa.PruductionManagement.Domain.Entities.Production.ProductionGroup", null)
                        .WithMany("ProductionItems")
                        .HasForeignKey("ProductionGroupId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Archive.ProductionGroupHistory", b =>
                {
                    b.Navigation("ProductionItems");
                });

            modelBuilder.Entity("Erfa.PruductionManagement.Domain.Entities.Production.ProductionGroup", b =>
                {
                    b.Navigation("ProductionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
